#!/bin/sh

###########
# RELEASE #
###########

echo 'RELEASING...'

sudo rsync -av --exclude='app/db' --exclude='app/logs' --exclude='.git' --exclude='.gitignore' --exclude='README.md' /var/music/repo/ /var/music/release

###################
# FIX PERMISSIONS #
###################

echo 'SETTING PERMISSIONS...'

## SET DEFAULT OWNER AND GROUP
sudo chown -R root  /var/music/release && \
sudo chgrp -R music /var/music/release

## SET DEFAULT PERMISSIONS
sudo find /var/music/release -type d | xargs sudo chmod 00770 && \
sudo find /var/music/release -type f | xargs sudo chmod ug=rw,o=

# CODE
sudo chgrp -R www-data /var/music/release/app/code && \
sudo find /var/music/release/app/code -type f | xargs sudo chmod ug+x

## DB
sudo chgrp -R mysql /var/music/release/app/db && \
sudo find /var/music/release/app/db -type f | xargs sudo chmod ug+x && \
sudo chgrp mysql /var/music/release/docker/db/mysql.cnf

## LOGS
sudo chgrp -R mysql    /var/music/release/app/logs/db && \
sudo find /var/music/release/app/logs/db -type f | xargs sudo chmod ug+x
sudo chgrp -R www-data /var/music/release/app/logs/web && \
sudo find /var/music/release/app/logs/web -type f | xargs sudo chmod ug+x

## STATIC
sudo chgrp -R www-data /var/music/release/app/static && \
sudo find /var/music/release/app/static -type f | xargs sudo chmod ug+x

## CONFIG PRIVATE
sudo find /var/music/release/config/private/prod/auth/db | xargs sudo chgrp mysql && \
sudo find /var/music/release/config/private/prod/ssl/db  | xargs sudo chgrp mysql && \
sudo find /var/music/release/config/private/prod/ssl/web | xargs sudo chgrp www-data

echo 'FINISHED... ROCK AND ROLL!!!'

