#!/bin/sh

###################
# FIX PERMISSIONS #
###################

echo 'START setting permissions'

## DOCKER
sudo find /var/music/docker -type f | xargs sudo chmod ug=rw,o= && \
sudo find /var/music/docker -type d | xargs sudo chmod g+w

## CONFIG
sudo find /var/music/config/public -type f | xargs sudo chmod ug=rw,o= && \
sudo find /var/music/config/public -type d | xargs sudo chmod g+w

# CODE
sudo chmod -R g=rwx /var/music/app/code

## STATIC
sudo chmod -R g=rwx /var/music/app/static

## GIT HOOKS
sudo chmod ug=rwx /var/music/.git/hooks/post-merge

echo 'END setting permissions'