version: '3.3'

services:
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    command: /bin/sh -c "envsubst '$$NGINX_HOST_NAME' < /etc/nginx/default.conf > /etc/nginx/conf.d/default.conf && while ! nc -w 1 -z db 3306; do sleep 0.1; done; nginx -g 'daemon off;'"
    environment:
     - NGINX_HOST_NAME
    volumes:
      - "phpsocket:/sock"
      - $SSL_CERTIFICATE_FOLDER:/etc/nginx/certs:ro
      - ./logs/web:/var/log/nginx
      - ./static:/var/www/static:ro
      - ./code:/var/www/code:ro
    networks:
      - backend-php
    ports:
      - "8000:80"
      - "443:443"
    depends_on:
      - db
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - "phpsocket:/sock"
      - ./code:/var/www/code:ro
    networks:
      - backend-php
    depends_on:
      - db

  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    environment:
     - MYSQL_ROOT_PASSWORD
     - MYSQL_DATABASE
     - MYSQL_USER
     - MYSQL_PASSWORD
    volumes:
     - $DB_CERTIFICATE_FOLDER:/etc/mysql/certs
     - ./db:/var/lib/mysql
     - ./logs/db:/var/log/mysql
    networks:
      - backend-php
    ports:
      - "3306:3306"

networks:
    backend-php:
        driver: bridge

volumes:
    phpsocket: