version: '3.3'

services:

  web:
    environment:
      - WEB_HOST_NAME=${DEV_WEB_HOST_NAME}
      - WEB_HOST_IP=${DEV_WEB_HOST_IP}
    volumes:
      - ${WEB_SSL_CERTIFICATE_FOLDER}/${DEV_FOLDER_NAME}:/etc/nginx/certs:ro

  php:
    env_file:
      - ${DB_PASSWORD_FOLDER}/${DEV_FOLDER_NAME}/${DB_USER_PASSWORD_FILE}

  db:
    env_file:
      - ${DB_PASSWORD_FOLDER}/${DEV_FOLDER_NAME}/${DB_ROOT_PASSWORD_FILE}
      - ${DB_PASSWORD_FOLDER}/${DEV_FOLDER_NAME}/${DB_USER_PASSWORD_FILE}
    volumes:
      - ${DB_SSL_CERTIFICATE_FOLDER}/${DEV_FOLDER_NAME}:/etc/mysql/certs:ro