version: '3.3'

services:

  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    command: /bin/sh -c "envsubst '$$WEB_HOST_NAME $$WEB_HOST_IP' < /etc/nginx/default.conf.raw > /etc/nginx/conf.d/default.conf && while ! nc -w 1 -z db 3306; do sleep 0.1; done; nginx -g 'daemon off;'"
    volumes:
      - ./code/php:/var/www/code/php:ro
      - ./logs/web:/var/log/nginx
      - ./static:/var/www/resource/static:ro
      - ./upload:/var/www/resource/upload
      - "sockets-volume-web-to-php:/sockets/web-to-php"
    networks:
      - backend-php-network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    environment:
      - MYSQL_HOST
      - MYSQL_SOCKET
      - MYSQL_DATABASE
      - MYSQL_USER
    volumes:
      - ./code/php:/var/www/code/php:ro
      - ./upload:/var/www/resource/upload
      - "sockets-volume-web-to-php:/sockets/web-to-php"
      - "sockets-volume-php-to-db:/sockets/php-to-db"
    networks:
      - backend-php-network
    depends_on:
      - db

  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
    volumes:
      - ./db:/var/lib/mysql
      - ./logs/db:/var/log/mysql
      - "sockets-volume-php-to-db:/var/run/mysqld"
    networks:
      - backend-php-network
    ports:
      - "3306:3306"

networks:
  backend-php-network:
    driver: bridge

volumes:
  sockets-volume-web-to-php:
  sockets-volume-php-to-db: