version: '3.3'

services:

  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    command: /bin/sh -c "envsubst '$$WEB_HOST_NAME' < /etc/nginx/default.conf > /etc/nginx/conf.d/default.conf && while ! nc -w 1 -z db 3306; do sleep 0.1; done; nginx -g 'daemon off;'"
    env_file:
      - ${TARGET_SPECIFIC_PUBLIC_ENV_FOLDER}/${CURRENT_ENV}/${TARGET_SPECIFIC_PUBLIC_ENV_FILE}
    volumes:
      - ${WEB_SSL_CERTIFICATE_FOLDER}/${CURRENT_ENV}:/etc/nginx/certs:ro
      - ./app/logs/web:/var/log/nginx
      - ./app/static:/var/www/static:ro
      - ./app/code/php:/var/www/code_php:ro
      - "phpsocket:/sock"
    networks:
      - backend-php
    ports:
      - "8000:80"
      - "443:443"
    depends_on:
      - db
      - php

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    env_file:
      - ${DB_PASSWORD_FOLDER}/${CURRENT_ENV}/${DB_USER_PASSWORD_FILE}
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
    volumes:
      - ./app/code/php:/var/www/code_php:ro
      - "phpsocket:/sock"
    networks:
      - backend-php
    depends_on:
      - db

  db:
    build:
      context: ./
      dockerfile: ./docker/db/Dockerfile
    env_file:
      - ${DB_PASSWORD_FOLDER}/${CURRENT_ENV}/${DB_ROOT_PASSWORD_FILE}
      - ${DB_PASSWORD_FOLDER}/${CURRENT_ENV}/${DB_USER_PASSWORD_FILE}
    environment:
      - MYSQL_DATABASE
      - MYSQL_USER
    volumes:
      - ${DB_SSL_CERTIFICATE_FOLDER}/${CURRENT_ENV}:/etc/mysql/certs:ro
      - ./app/db:/var/lib/mysql
      - ./app/logs/db:/var/log/mysql
    networks:
      - backend-php
    ports:
      - "3306:3306"

networks:
  backend-php:
    driver: bridge

volumes:
  phpsocket: