#!/bin/sh

###########
# RELEASE #
###########

echo 'RELEASING CODE...'

sudo rsync -av --exclude='db' --exclude='logs' --exclude='.git' --exclude='.gitignore' --exclude='README.md' /var/music/git/ /var/music/release

echo 'UPDATING GIT HOOKS...'

sudo rsync -av /var/music/release/config/public/hooks/* /var/music/git/hooks

###################
# FIX PERMISSIONS #
###################

echo 'SETTING PERMISSIONS...'

## SET DEFAULT OWNER AND GROUP
sudo chown -R root  /var/music/release && \
sudo chgrp -R music /var/music/release

## SET DEFAULT PERMISSIONS
sudo find /var/music/release -type d | xargs sudo chmod ug=rw,o=rx && \
sudo find /var/music/release -type f | xargs sudo chmod ug=rw,o=

# CODE
sudo chmod o= /var/music/release/code && \
sudo chgrp -R www-data /var/music/release/code && \
sudo find /var/music/release/code -type f | xargs sudo chmod g+x

## DB
sudo chmod o= /var/music/release/db && \
sudo chgrp -R mysql /var/music/release/db

## LOGS: DB
sudo chmod o= /var/music/release/logs/db && \
sudo chgrp -R mysql /var/music/release/logs/db

## LOGS: WEB
sudo chmod o= /var/music/release/logs/web && \
sudo chgrp -R www-data /var/music/release/logs/web

## STATIC
sudo chmod o= /var/music/release/static && \
sudo chgrp -R www-data /var/music/release/static

## CONFIG PRIVATE
sudo chmod -R o=       /var/music/release/config/private/prod/auth/db && \
sudo chgrp -R mysql    /var/music/release/config/private/prod/auth/db && \
sudo chmod -R o=       /var/music/release/config/private/prod/ssl/db && \
sudo chgrp -R mysql    /var/music/release/config/private/prod/ssl/db && \
sudo chmod -R o=       /var/music/release/config/private/prod/ssl/web && \
sudo chgrp -R www-data /var/music/release/config/private/prod/ssl/web

## GIT HOOKS
sudo chown -R root  /var/music/git && \
sudo chgrp -R music /var/music/git && \
sudo find /var/music/git -type d | xargs sudo chmod ug=rwx,o= && \
sudo find /var/music/git -type f | xargs sudo chmod ug=rw,o= && \
sudo chmod ug=rwx /var/music/git/.git/hooks/*

echo 'FINISHED... ROCK AND ROLL!!!'
