#!/bin/sh

###########
# RELEASE #
###########

echo 'RELEASING CODE...'

sudo rsync -av --exclude='db' --exclude='log' --exclude='script' --exclude='secret' --exclude='upload' --exclude='.git' --exclude='.gitignore' --exclude='README.md' /var/music/git/ /var/music/release

echo 'UPDATING GIT HOOKS...'

sudo rsync -av /var/music/git/script/hooks/* /var/music/git/.git/hooks

###################
# FIX PERMISSIONS #
###################

echo 'SETTING PERMISSIONS...'

## SET DEFAULT OWNER AND GROUP
sudo chown -R root  /var/music/release && \
sudo chgrp -R music /var/music/release

## SET DEFAULT PERMISSIONS
sudo find /var/music/release -type d | xargs sudo chmod ug=rw,o=rx && \
sudo find /var/music/release -type f | xargs sudo chmod ug=rw,o=

# CODE
sudo chmod -R o=       /var/music/release/code && \
sudo chgrp -R www-data /var/music/release/code && \
sudo find /var/music/release/code -type f | xargs sudo chmod g+x

## DB
sudo chmod -R o=    /var/music/release/db && \
sudo chgrp -R mysql /var/music/release/db

## DOCKER
sudo chmod -R o= /var/music/release/docker && \
sudo chmod ug+x  /var/music/release/docker/db/docker-entrypoint.sh && \
sudo chmod ug+x  /var/music/release/docker/php/docker-php-*

## LOGS: DB
sudo chmod -R o=    /var/music/release/log/db && \
sudo chgrp -R mysql /var/music/release/log/db

## LOGS: WEB
sudo chmod -R o=       /var/music/release/log/web && \
sudo chgrp -R www-data /var/music/release/log/web

## SCRIPT
sudo chmod -R o= /var/music/release/script

## SECRET
sudo chmod -R o=       /var/music/release/secret/prod/auth/db && \
sudo chgrp -R mysql    /var/music/release/secret/prod/auth/db && \
sudo chmod -R o=       /var/music/release/secret/prod/ssl/db && \
sudo chgrp -R mysql    /var/music/release/secret/prod/ssl/db && \
sudo chmod -R o=       /var/music/release/secret/prod/ssl/web && \
sudo chgrp -R www-data /var/music/release/secret/prod/ssl/web

## STATIC
sudo chmod -R o=       /var/music/release/static && \
sudo chgrp -R www-data /var/music/release/static

## UPLOAD
sudo chmod -R o=       /var/music/release/upload && \
sudo chgrp -R www-data /var/music/release/upload

## GIT HOOKS
sudo chown -R root  /var/music/git && \
sudo chgrp -R music /var/music/git && \
sudo find /var/music/git -type d | xargs sudo chmod ug=rwx,o= && \
sudo find /var/music/git -type f | xargs sudo chmod ug=rw,o= && \
sudo chmod ug=rwx /var/music/git/.git/hooks/*

echo 'FINISHED... ROCK AND ROLL!!!'
